---
language: java

before_install:
    - sudo apt-get install jq
    - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

install: /bin/true

jdk:
- oraclejdk8

before_script:
    - wget https://services.gradle.org/distributions/gradle-3.3-bin.zip
    - unzip gradle-3.3-bin.zip
    - export GRADLE_HOME=$PWD/gradle-3.3
    - export PATH=$GRADLE_HOME/bin:$PATH

script:
- ./gradlew assemble
- ./gradlew check


after_success:
    - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/test-results/jacoco/test/jacocoTestReport.xml
